### ISSUE TITLE
Wrong tags on Open Hours: Current Status

### ISSUE THREAD

**Issue by oanafilip** [pixelgrade/open#11]
@andreistangacianu - label-urile din _Customizer -> Widgets -> Open Hours: Current Status_ și cele afișate în imaginea făcută de @georgeolaru sunt diferite. 
Într-o parte e {today-closing-time} și în cealaltă  {today-end-time}: https://cl.ly/08250T3i0I3r
La fel și pentru {next-opening-time} și {next-start-time}. Cred că merită luate toate la verificat. :)

**Comment by raduconst** [comment]
@oanafilip Pare ca imaginea din plugin:
![opening_hours_scheme](https://user-images.githubusercontent.com/6512220/29752867-828a40de-8b6e-11e7-8f52-b103a80a938f.png)
difera de cea adaugata de tine, in screenshot: https://cl.ly/08250T3i0I3r
@georgeolaru Care e varianta finala? Ma pot ocupa eu de verificari insa ma gandesc ca poate s-au "schimbat planurile" intre timp.

**Comment by georgeolaru** [comment]
Aici cred ca @andreistangacianu stie mai bine cum s-a intamplat — am impresia ca imaginea din plugin e cea buna, fiind editata in urma unor schimbari de tag-uri.

**Comment by raduconst** [comment]
Am verificat tag-urile in cod si sunt cele din imaginea din plugin. In cazul asta, toate-s bune :-)
