### ISSUE TITLE
Wrong link on the Front Page Hero Widgets (Customizer)

### ISSUE THREAD

**Issue by oanafilip** [pixelgrade/open#4]
@andreistangacianu - nu merge link-ul de pe Front Page Hero Widgets (Open Hours Overview) - Learn more about time formatting: https://cl.ly/2Q2b0w0u1P1C

La Footer Area te duce unde trebuie, adică aici: https://codex.wordpress.org/Formatting_Date_and_Time

**Comment by Robertght** [comment]
@oanafilip, @andreistangacianu acum apare asa daca dai click pe available tags:
![image](https://user-images.githubusercontent.com/6737345/30064319-030da538-925a-11e7-9620-0fc13531cd70.png)

Mai este valabil?
