### ISSUE TITLE
Write docs

### ISSUE THREAD

**Issue by andreistangacianu** [pixelgrade/open#9]
In sectiunea “Open Hours” link-ul de la Learn more about setting hours ar trebui sa duca undeva in documentatie.

**Comment by raduconst** [comment]
@andreistangacianu Vad ca a fost creat, intre timp, un articol despre Open Hours: https://pixelgrade.com/docs/osteria/plugins-integrations/adding-opening-hours-system/
Mai e de actualitate issue-ul?

**Comment by Robertght** [comment]
@andreistangacianu Aici vad ca apare acea imagine cu tag-urile. Mai este valabil issue-ul?

**Comment by georgeolaru** [comment]
All good aici! 🙏
